/*
 * This source file was generated by the Gradle 'init' task
 */
package incidents

import io.grpc.Server
import io.grpc.ServerBuilder

// Preload repository with sample data
import incidents.loadSampleData

/**
 * Entry point for the gRPC server.
 */
fun main() {
    loadSampleData()
    val server: Server = ServerBuilder.forPort(9090)
        .addService(IncidentServiceImpl())
        .build()

    server.start()
    println("Server started on port 9090")
    server.awaitTermination()
}
